### ISSUE TITLE
[#22] set up continous integration tool integrated with github which runs test automatically

### ISSUE THREAD

**Issue by grzegorzborkowski** [grzegorzborkowski/judge#22]

**Comment by annaaniol** [comment]
Przeglądnęłam kilka continous integration tools na githubie. Travis CI wygląda dobrze, ma prostą instrukcję konfiguracji, wspiera Dockera i jest zintegrowany ze Slackiem. Tylko właściciel repo może go postawić. [https://github.com/integrations/travis-ci](https://github.com/integrations/travis-ci)

**Comment by grzegorzborkowski** [comment]
Zrobione z https://github.com/grzegorzborkowski/judge/pull/30
