### ISSUE TITLE
Adjust frontend -  problem views

### ISSUE THREAD

**Issue by tusty53** [grzegorzborkowski/judge#58]
1. Font size of name, description, and output should match code font size.
2. Fields in problem creation/edition/submission should be separated.
3. Structures field n submissions should be resized to match the length of the code.
4. Number of test shouldn't be shown when compilation fails.
5. Time should have the unit and should be shortened to show only important information
    i.e. 5 min instead of 300.00123 seconds
6. Immutable code could have different coloring that the mutable one.

**Comment by annaaniol** [comment]
done with #81
