### ISSUE TITLE
Improve submissions view

### ISSUE THREAD

**Issue by tusty53** [grzegorzborkowski/judge#61]
1. Passed tests/all tests should be in one column, percentage shouldn't be shown.
2. Each submission should have submission time.
3. Submissions should be listed from most to least recent.
4. Problem id shoudn't be shown in submissions view. 
5. Name of the problem should be shown in title of per-problem submission page.
6. Compilation/execution codes should be reviewed.

**Comment by annaaniol** [comment]
done with #81
